forge "http://forge.puppetlabs.com"

mod 'puppetlabs/razor',     :git => 'https://github.com/nanliu/puppetlabs-razor.git', :ref=>'tb/resource'
mod 'puppetlabs/dhcp',      :git => 'https://github.com/puppetlabs/puppetlabs-dhcp.git'
mod 'saz/sudo',             :git => 'https://github.com/saz/puppet-sudo.git'
mod 'cprice404/inifile' 
mod 'puppetlabs/mongodb'
mod 'puppetlabs/apt'
mod 'puppetlabs/nodejs'
mod 'puppetlabs/tftp'
mod 'puppetlabs/vcsrepo'
mod 'ripienaar/concat',     :git => 'https://github.com/ripienaar/puppet-concat.git'
mod 'puppetlabs/ruby'
mod 'puppet/puppet',        :git => 'git://github.com/stephenrjohnson/puppetlabs-puppet.git'
mod 'puppetlabs/apache', :git => 'git://github.com/puppetlabs/puppetlabs-apache', :ref => '94ebca3aaaf2144a7b9ce7ca6a13837ec48a7e2a'
mod 'puppet/puppetdb',      :git => 'git://github.com/stephenrjohnson/puppetlabs-puppetdb.git'
