desc 'clone all required modules'
  task :setup do
      puts "Running setup task"
      
      sh %(librarian-puppet install)
      if File.exists?("images/ubuntu-12.04-server-amd64.iso")
          puts "Image file already downloaed please delete if you wish to download again"
      else
          puts "Download ubuntu install image, this may take a long time"
          sh %("curl http://releases.ubuntu.com/12.04/ubuntu-12.04-server-amd64.iso > images/ubuntu-12.04-server-amd64.iso")
      end
  end
